options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'chennapragada-flask-instance'
      - '--zone=us-central1-a'
      - '--container-image=gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:$COMMIT_SHA'

substitutions:
  _COMMIT_SHA: "${SHORT_SHA}"
