options:
  logging: CLOUD_LOGGING_ONLY  # Keeps logs only in Cloud Logging, not in a bucket

steps:
  # Step 1: Pull the latest image (ensures it's available)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - 'gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:latest'

  # Step 2: Push the Docker image again to Artifact Registry (forces an update)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:latest'

  # Step 3: Deploy the updated container to Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'chennapragada-flask'  # Instance name
      - '--zone=us-central1-a'
      - '--container-image=gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:latest'
      - '--clear-container-command'  # Clears the old command if necessary

substitutions:
  _COMMIT_SHA: "${SHORT_SHA}"
