options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Add/update the container declaration metadata on the instance.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud compute instances add-metadata chennapragada-flask \
          --zone=us-central1-a \
          --metadata=gce-container-declaration="spec:\n  containers:\n  - name: chennapragada-flask\n    image: gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:$COMMIT_SHA\n  restartPolicy: Always"

  # Step 2: Build the Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:$COMMIT_SHA', '.']

  # Step 3: Push the Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:$COMMIT_SHA']

  # Step 4: Update the container on the instance.
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'chennapragada-flask'
      - '--zone=us-central1-a'
      - '--container-image=gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app:$COMMIT_SHA'

substitutions:
  _COMMIT_SHA: "${SHORT_SHA}"
