steps:
  # Authenticate Docker with GCR
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'gcr.io']

  # SSH into the VM and pull the latest Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'chennapragada-flask', '--zone=us-central1-a', '--command',
           'docker pull gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app']

  # Stop the existing container (if any) and run a new one
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'chennapragada-flask', '--zone=us-central1-a', '--command',
           'docker stop $(docker ps -q) || true && docker run -d -p 5000:5000 gcr.io/supple-gearbox-447219-d0/chennapragada-flask-app']

  # OPTIONAL: Build and push a new Docker image (only if needed)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chennapragada-flask-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chennapragada-flask-app']

options:
  logging: CLOUD_LOGGING_ONLY
